### ISSUE TITLE
Central & Peripheral dual-role

### ISSUE THREAD

**Issue by awellig** [don/cordova-plugin-ble-peripheral#1]
I need to be able to support a dual GAP role scenarios, i.e. the device can be both a Central and a Peripheral. For that reason I included both cordova plugins: "cordova-plugin-ble-peripheral" and "cordova-plugin-ble-central". Unfortunately, the Phonegap build process results in a duplicate symbol error:

_duplicate symbol _dataToArrayBuffer in:
    /project/build/Microfence.build/Release-iphoneos/Microfence.build/Objects-normal/armv7/BLEPeripheralPlugin.o
    /project/build/Microfence.build/Release-iphoneos/Microfence.build/Objects-normal/armv7/CBPeripheral+Extensions.o_

Any chance to change the naming conventions, or do enhance the ble-central library with advertising capabilities?

**Comment by don** [comment]
Fixed by #3
