### ISSUE TITLE
Could You suggest a BLE peripheral, Apache Cordova plugin, for Android?

### ISSUE THREAD

**Issue by sigurko** [don/cordova-plugin-ble-peripheral#2]
This is a cool peripheral plugin You've got here, thanks for sharing it.

Not an issue, just wanted to ask a question, and hope that others can benefit from the answer:
Are You aware of any other Peripheral Plugins for Android?

AFAIK, it's supported starting Android 5 (Lollipop) on devices with proper hardware, such as Nexus 5X and 6, for an example.
However, I could not find any Cordova peripheral plugins for Android...

BTW, the reason I'm asking You this question is because googling for:
"central" "peripheral" "cordova"
has first 3-4 search results pointing back to You =)

Thanks,
Matthew.

**Comment by faridportal** [comment]
@sigurko did you find any peripheral plugin for android?

**Comment by maske94** [comment]
Did someone find out any plug-in for Android ? Thank you :)

**Comment by faridportal** [comment]
@maske94 yeah I have written a prototype app with "cordova-plugin-bluetoothle" plugin its URL is: https://github.com/randdusing/ng-cordova-bluetoothle

**Comment by don** [comment]
Version 1.0.0 of this plugin (https://www.npmjs.com/package/cordova-plugin-ble-peripheral) supports Android.

/cc @maske94 @faridportal @sigurko
