### ISSUE TITLE
Multiple services on display

### ISSUE THREAD

**Issue by shastry-chamarthi** [don/cordova-plugin-ble-peripheral#4]
Hi @don , 

I tried to use this plugin and found that it's add more than the "asked". Say, I have added 1 service with 1 characteristic, it's adding more than 1 services which are generic like battery service, heart rate, etc. 

Let me know if there's anything I'm missing. 

Regards.

**Comment by don** [comment]
This plugin allows your app to publish one or more services. Other apps on your phone can still publish services. Most devices publish Generic Access (0x1800) and Generic Attribute (0x1801) services. iPhones also publish Battery Service, Current Time Service, ANCS, etc. I think you're seeing the correct behavior.

**Comment by shastry-chamarthi** [comment]
Thank you Don.
